/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import gestionrequerimientos.BaseDatos;
import java.util.ArrayList;

/**
 *
 * @author queimel
 */
public class ConsultarReq extends javax.swing.JFrame {

    private final BaseDatos miBD = new BaseDatos();
    /**
     * Creates new form ConsultarReq
     */
    public ConsultarReq() {
        initComponents();
        cargarCBO("gerencia", cb_gerencia);
        cargarCBO("asignacion", cb_asignar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_gerencia = new javax.swing.JLabel();
        cb_gerencia = new javax.swing.JComboBox<>();
        lbl_depto = new javax.swing.JLabel();
        cb_depto = new javax.swing.JComboBox<>();
        lbl_asignar = new javax.swing.JLabel();
        cb_asignar = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_requerimientos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Consultar Requerimientos");

        lbl_gerencia.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbl_gerencia.setText("Gerencia:");

        cb_gerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        cb_gerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_gerenciaActionPerformed(evt);
            }
        });

        lbl_depto.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbl_depto.setText("Depto.:");

        cb_depto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        lbl_asignar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbl_asignar.setText("Asignado a:");

        cb_asignar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        cb_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_asignarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        tbl_requerimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Gerencia", "Departamento", "Asignado a", "Requerimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_requerimientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_gerencia)
                                    .addComponent(lbl_depto)
                                    .addComponent(lbl_asignar))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_asignar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_depto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(btn_buscar)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gerencia)
                    .addComponent(cb_gerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_depto)
                    .addComponent(cb_depto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_asignar)
                    .addComponent(cb_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_gerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_gerenciaActionPerformed
        int gerencia = cb_gerencia.getSelectedIndex();
        cargarDepto(gerencia, cb_depto);
    }//GEN-LAST:event_cb_gerenciaActionPerformed

    private void cb_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_asignarActionPerformed

    }//GEN-LAST:event_cb_asignarActionPerformed

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        int gerencia = cb_gerencia.getSelectedIndex();
        int depto = cb_depto.getSelectedIndex();
        int asignacion = cb_asignar.getSelectedIndex();
        
        miBD.consultaRequerimientos(gerencia, depto, asignacion, tbl_requerimientos);
    }//GEN-LAST:event_btn_buscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarReq().setVisible(true);
            }
        });
    }
    
    public void cargarCBO(String key, javax.swing.JComboBox<String> combo){
        combo.removeAllItems();
        combo.addItem("Seleccionar");
        ArrayList<String> listaCBO = miBD.cargarCB(key);
        for (int i = 0; i < listaCBO.size(); i++) {
            String item = listaCBO.get(i);
            combo.addItem(item);  
        }
    }
    
    public void cargarDepto(int gerencia, javax.swing.JComboBox<String> combo){
        combo.removeAllItems();
        combo.addItem("Seleccionar");
        ArrayList<String> listaCBO = miBD.cargarCBDepto(gerencia);
        for (int i = 0; i < listaCBO.size(); i++) {
            String item = listaCBO.get(i);
            combo.addItem(item);  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JComboBox<String> cb_asignar;
    private javax.swing.JComboBox<String> cb_depto;
    private javax.swing.JComboBox<String> cb_gerencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_asignar;
    private javax.swing.JLabel lbl_depto;
    private javax.swing.JLabel lbl_gerencia;
    private javax.swing.JTable tbl_requerimientos;
    // End of variables declaration//GEN-END:variables
}
